services:
  api:
    build:
      context: ./hybrid-ocr-api
    ports:
      - "8000:8000"
    env_file:
      - .env

  worker:
    build:
      context: ./hybrid-ocr-worker
    env_file:
      - .env

    deploy: {}  # ignore ไปเลย

    runtime: nvidia

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
